# Example of Stereo Pair topic Names == "sensor_name"
sensor_name/left_image_topic: "left/image_color"
sensor_name/right_image_topic: "right/image_color"
sensor_name/left_image_rec_topic: "left/image_rect_color" 
sensor_name/right_image_rec_topic: "right/image_rect_color"
sensor_name/stereo_info_topic: "stereo_info"

sensor_name/image_topic: "stereo/image_color"
sensor_name/depth_image_topic: "stereo/depth"
sensor_name/camera_info_topic: "stereo/camera_info"
sensor_name/xyzrgb_topic: "stereo/points"

sensor_name/sensor_link: "sensor_name/left_frame"